pipeline {
    agent any 
    stages{
        stage('BUILD') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage"
                '''
            }
        }

        stage('BUILD1.1') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD1.1 stage"
                '''
            }
        }

        stage('BUILD1.2') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD1.2 stage"
                '''
            }
        }
 
        stage('TEST') {
            steps{
                sh '''
                    sleep 5
                    echo "This is a TEST stage"
                '''
            }
        }

        stage('DEPLOY') {
            steps{
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage"
                '''
            }
        }
    }
}
